---
- name: "keepalived"
  yum: name=keepalived state=installed 

- name: "haproxy"
  yum: name=haproxy state=installed

- name: "Start keepalived"
  service: name=keepalived state=running enabled=yes

- name: "Start haproxy"
  service: name=haproxy state=running enabled=yes
